name: Brimstone Server CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pr:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set node env
        uses: allenevans/set-env@v1.0.0
        with:
          NODE_ENV: production

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          PORT: ${{ secrets.PORT }}
          RIOT_DEV_API_KEY: ${{ secrets.RIOT_DEV_API_KEY }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
      - run: |
          npm ci
          npm run test:ci
