name: Brimstone Server PR CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          PORT: ${{ secrets.PORT }}
          RIOT_DEV_API_KEY: ${{ secrets.RIOT_DEV_API_KEY }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
      - run: npm ci
      - run: npm test
